---
title: "callie_test"
author: "Callie Steffen,"
date: "3/10/2020"
output: html_document
---
```{r}

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(janitor)
library(tidyverse)
```

```{r, fig.width= 40, fig.height= 20}
# Data Exploration
#drop NAS only want ships with IHS data
#sort by NOAA score reported-Top performers A+- export as csv!
#distribution from all IHS data and breakdown of letter grade by type
#Biggest discrepancies.. biggest players that mis represent?
#Re categorize for smaller ship type samples

# Arrange Ship Stats By Dropping NAs and rename column of compliance. Arrange in descending order so we can get the top performers that have 100

ship_stats <- read_csv("ship_stats.csv")
#ship_stats <- ship_stats %>% 
  #rename(c("com_score_reported" ="compliance score (reported speed)"))

stats_ihs <-ship_stats %>% 
  drop_na() %>% 
  arrange(-com_score_reported)

#111 vessels with A+ /100 score

top_performers <- stats_ihs %>% 
  head(111) %>% #exported as CSV
  group_by(ship_type_ihs) %>% 
  count(ship_type_ihs)

#Quantity of Each letter grade and ship type 

grades <- stats_ihs %>% 
  group_by(grade) %>% 
 count(grade)
 
grade_quantity <- stats_ihs %>% 
  group_by(grade) %>% 
  count(ship_type_ihs)

 #Distrubution of all letter grades by vessel type (how many of each vessel type is getting each letter grade)
letter_plot <- ggplot(grade_quantity, aes(fill= ship_type_ihs, y= n, x=grade)) + 
    geom_bar(position="stack", stat="identity")

letter_plot

  


```

#Interested in seeing distrubution of categories 

```{r}

ihs_type_category <- stats_ihs %>%
  mutate(
    category = case_when(
      ship_type_ihs %in% c("Tug","Articulated Pusher Tug","Pusher Tug","Anchor Handling Tug Supply") ~ "Tug",
      ship_type_ihs %in% c("Bulk Carrier","Vehicles Carrier","Wood Chips Carrier","Heavy Load Carrier","Bulk Carrier, Self-discharging") ~ "Carrier",
      ship_type_ihs %in% c("Crude Oil Tanker","Chemical/Products Tanker", "Crude/Oil Products Tanker", "Products Tanker", "Replenishment Tanker","LPG Tanker","LNG Tanker","Chemical Tanker") ~ "Tanker",
      ship_type_ihs %in% c("General Cargo Ship","Replenishment Dry Cargo Vessel","Open Hatch Cargo Ship","Logistics Vessel (Naval Ro-Ro Cargo)","General Cargo Ship (with Ro-Ro facility)","Refrigerated Cargo Ship", "Ro-Ro Cargo Ship" ) ~ "Cargo",
      ship_type_ihs%in%c("Research Survey Vessel","Fishery Research Vessel") ~"Research",
      ship_type_ihs%in%c( "Yacht","Yacht (Sailing)") ~"Yacht",
      ship_type_ihs%in%c( "Passenger/Cruise","Passenger Ship") ~"Passenger",
      ship_type_ihs%in%c("Landing Craft","Frigate","Work/Maintenance Pontoon,non propelled","Icebreaker","Crew/Supply Vessel","Drilling Ship","Pollution Control Vessel","Cable Layer", "Hopper,Motor","Salvage Ship","Cable Repair Ship","Training Ship","Utility Vessel","Trailing Suction Hopper Dredger") ~ "Other",
      ship_type_ihs%in%c("Platform Supply Ship") ~"Platform Supply Ship",
      ship_type_ihs%in%c("Container Ship (Fully Cellular)","Container Ship (Fully Cellular/Ro-Ro Facility)") ~"Container Ship",
      ship_type_ihs%in%c("Fishing Vessel") ~ "Fishing Vessel"))
   









# Count Grades Per Category
category_quantity <- ihs_type_category %>% 
  group_by(grade) %>% 
  count(category)

# Now Plot For Categories

letter_plot_category <-ggplot(category_quantity, aes(fill= category, y= n, x=grade)) + 
    geom_bar(position="stack", stat="identity")

letter_plot_category

                                       

```

# Categories With Time Discrepancies 

```{r}
reporting_differences <- ihs_type_category %>% 
  mutate(diff_in_score = as.numeric(com_score_reported - `compliance score (calculated speed)`))

category_differnces <- reporting_differences %>% 
  group_by(category) %>%
  summarize(total_cat = sum(diff_in_score))


  

```


#Categories of Main Interst: Tankers, Bulk, and Container - what is all considered "passenger" - Lets look at carrier (bulk), cargo,tankers,container

```{r}
# filter out for categories of interest

interest <- ihs_type_category %>% 
  filter(category == "Cargo"| category == "Carrier" | category == "Tanker" | category == "Container Ship")

```

# How many ship types does each operators have and how many of each?
```{r}
#467 operators total
#530 operators = 63 operators that have more than one ship type

# amount of each ship type for each operator
operators_shiptypes <- stats_ihs %>%
  group_by(operator) %>% 
  count(ship_type_ihs)

```

```{r}

#operator and how many ship types they own
distinct_ships <- stats_ihs %>%
  select(operator,ship_type_ihs,`total distance (nautcal miles)`) %>% 
  group_by(operator) %>% 
  summarise(types = n_distinct(ship_type_ihs))

# total amount of nautical miles travelled by each operator
                               
 distinct_ships_2 <- stats_ihs %>%
  select(operator, `total distance (nautcal miles)`) %>% 
  group_by(operator) %>% 
  summarize(total_trav = sum(`total distance (nautcal miles)`))
 
 ## combine by operator so we can see how many ship types and distance.

operators_2 <- full_join(distinct_ships,distinct_ships_2)
                                                     
```

